version: '2'
services:
    jhipstermicroserviceapplication-app:
        image: jhipstermicroserviceapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermicroserviceapplication-mysql:3306/jhipstermicroserviceapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstermicroserviceapplication-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    jhipstermicroserviceapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstermicroserviceapplication-mysql
    jhipstermicroserviceapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstermicroserviceapplication-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
